CLASS zcl_avion_dnavas DEFINITION ABSTRACT
  PUBLIC
*  FINAL
  CREATE PUBLIC .
  PUBLIC SECTION.
    METHODS velocidad_avion ABSTRACT RETURNING VALUE(r_value) type string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_avion_dnavas IMPLEMENTATION.
ENDCLASS.
